version: "3.8"

services:
  app:
    build: .
    container_name: api-livro
    ports:
      - "8000:8000"
    volumes:
      - .:/app:Z
    env_file:
      - .env
    command: ["poetry","run","uvicorn","main:app","--host","0.0.0.0","--port", "8000"]

    deploy: 
      replicas: 5
      restart_policy: 
        condition: on-failure
  redis:
    image: redis:alpine
    container_name: api-redis
    ports:
      - "6379:6379"